Repository imcf/python-imcflibs, pull requests merged in 2025-03, with the labels that each got.

#44 Enable automatic ruff linting
  .github/workflows/lint.yml
  pyproject.toml
Labels: enhancement, documentation, next-release, conventions

#48 Add some pathtools tests
  src/imcflibs/pathtools.py
  tests/test_pathtools.py
Labels: unit testing

#39 Update for latest version BigStitcher, add fusion (BDV-playground)
  src/imcflibs/imagej/bdv.py
  src/imcflibs/imagej/misc.py
  src/imcflibs/imagej/objects3d.py
  tests/bdv/test_define_dataset_auto.py
  tests/bdv/test_definitionoptions.py
  tests/bdv/test_processingoptions.py
  tests/bdv/test_processingoptions_example3.py
  tests/bdv/test_processingoptions_example4.py
Labels: enhancement, next-release

#54 Remove docstrings for internal globals
  src/imcflibs/imagej/bdv.py
Labels: documentation, conventions

#55 BDV docstrings
  src/imcflibs/imagej/bdv.py
Labels: documentation, next-release, conventions

#49 Add more methods following the coding session of 2025 03 11
  src/imcflibs/imagej/bioformats.py
  src/imcflibs/imagej/labelimage.py
  src/imcflibs/imagej/misc.py
  src/imcflibs/imagej/objects3d.py
  src/imcflibs/imagej/omerotools.py
  src/imcflibs/imagej/processing.py
  src/imcflibs/imagej/shading.py
  src/imcflibs/pathtools.py
Labels: enhancement, unit testing, next-release, next-coding-session

#63 Change log updates for 1.5.0 release
  CHANGELOG.md
Labels: documentation

#65 Rename function to `apply_rollingball_bg_subtraction()`
  src/imcflibs/imagej/processing.py
Labels: enhancement

#66 Update documentation for OMERO tools requirements
  src/imcflibs/imagej/omerotools.py
Labels: documentation

#67 Add notes to calculate_mean_and_stdv for empty input handling
  src/imcflibs/imagej/misc.py
Labels: documentation

#68 Fix indentation of function
  src/imcflibs/imagej/omerotools.py
Labels: bug

#69 Fix `fix_ij_options` docstring and set tested options
  src/imcflibs/imagej/prefs.py
Labels: documentation

#70 Attempt to fix docstring rendering in pdoc
  src/imcflibs/imagej/misc.py
Labels: documentation
