Repository imcf/python-imcflibs, pull requests merged in 2025-04, with the labels that each got.

#76 Add usage instructions
  tests/interactive-imagej/send-notification-email.md
Labels: documentation, unit testing

#74 Changes to bioformats module's metadata retrieval
  CHANGELOG.md
  src/imcflibs/imagej/bioformats.py
  src/imcflibs/imagej/prefs.py
  tests/interactive-imagej/bioformats/metadata/test_metadata.md
Labels: enhancement, documentation, unit testing

#80 Add methods for `imcflibs.imagej.processing`
  CHANGELOG.md
Labels: documentation

#81 Update changelog
  CHANGELOG.md
Labels: documentation

#87 Explain IJ options `iterations` and `count`
  src/imcflibs/imagej/prefs.py
Labels: documentation

#88 Final changes for the `imcflibs-1.5.0` release
  .github/workflows/build.yml
  .github/workflows/dispatch-deploy-pages.yml
  .github/workflows/lint.yml
  .github/workflows/pytest-poetry.yml
  .github/workflows/pytest-python2.yml
  .gitignore
  .vscode/settings.json
  .vscode/tasks.json
  CHANGELOG.md
  DEVELOPMENT.md
  README.md
  TESTING.md
  poetry.lock.md
  pyproject.toml
  src/imcflibs/imagej/prefs.py
Labels: next-release
